### ISSUE TITLE
Thickbox and auto update cart

### ISSUE THREAD

**Issue by noisysomeone** [wojodesign/simplecart-js#124]
Hi,

How to integrate changes in cart in thickbox with cart on page? If i delete items in thickbox and close it items in cart on site are the same. When i reload page i can see the changes in my cart. Thickbox inframe.

**Comment by iamstevemckinney** [comment]
Is there anyway to not use an iframe in your thickbox? Without a link to the page you're experience the problem with i can only guess, but what is happening is that when you update your simpleCart cart it'll update everything on its own page, and then store that info in a cookie so it can retrieve it when you load a new page all of the information will still be there.

Since you're updating things in an iframe it doesn't have access to update the items on your main page and can only store the changes in the cookie, thus why it only shows up on refresh.

**Comment by noisysomeone** [comment]
iamstevemckinney, exactly as you written. http://zegarki-jelly.pl
