### ISSUE TITLE
Prices with tax included

### ISSUE THREAD

**Issue by Dudikowski** [wojodesign/simplecart-js#137]
Here is Sweden it is customary to show consumer prices with tax included, but when a company is the buyer prices are shown without tax (added in the checkout). In more advanced shops the visitor can choose how to show prices. Companies can deduct the tax but customers can not which is the reason for this.

I have my first simplecart solution in it's final stages and it is a shop for customers. So the best solution would be to just show a price and in the information on the main page inform that the prices are with tax included.

But the problems comes with the Paypal checkout. It is also customary here that such a customer checkout shows how much of the total price the tax is. But if I turn off tax in the script then the Paypal checkout naturally say nothing about taxes either.

So it's like this:

Consumer shop
Price: 100 kr

Checkout:

Price: 100 kr
of which is tax: 20 kr

Sum to pay: 100 kr 

---

Company shop

Price: 80 kr

Checkout:

Price: 80 kr
Tax: 20 kr

Total 100 kr

---

So I have the company version working. How can I turn this into the customer version? Can something be done in the simplecart script or over at Paypal?

**Comment by topguncharl** [comment]
I have exactly the same question - have you found a way to solve this ?

**Comment by Dudikowski** [comment]
No unfortunately not. I need help from the community to fix this.

**Comment by brettwejrowski** [comment]
I'm not sure if there is a way for PayPal to display the information this way... It could be possible in simpleCart(js) a number of ways though.  You could display the total price in the shelf item, but have a hidden input with the price without tax, so that it is calculated separate from what is shown when people are shopping.  Another option is to have a custom value for the item that has the text of "X from tax" which calculates and displays the part of the item cost that is tax.  This custom value will also be displayed under the item in PayPal, which may solve your problem.
