### ISSUE TITLE
Maximum inventory quantity?

### ISSUE THREAD

**Issue by rothgar** [wojodesign/simplecart-js#164]
Is there a way to set a total inventory quantity and then have simplecart deduct from that total each time a purchase is made (thus making the available item smaller for each user)? Your tool looks great but I would need some way to set how many of a single item I have.
I think this functionality may require a database to store that information centrally but I wanted to ask anyway.
As a side note, the wiki page about email checkout appears to be blank but I will look elsewhere to solve that problem.

**Comment by brettwejrowski** [comment]
Yeah you would need some kind of independent data to check against for updating the quantity.  You could probably work in a script that sends the total purchased after checkout or something, which could update that total on a server.  And then load that same total in on the cart pages.

**Comment by hughbones** [comment]
Would you know how to specify the order details to get them posted back to your website after checkout, from Paypal? 

I know that the following would return the user to your website after checkout
simpleCart.successUrl = "http://your-domain.com/"; 
- But how would you specify the details of that order - perhaps an item ID and the quantity of each item to be returned for processing so that inventory levels can be updated.

Cheers.
