### ISSUE TITLE
V3 and Send Form, need help...

### ISSUE THREAD

**Issue by ghost** [wojodesign/simplecart-js#171]
Hello,

I am you could say a noob when it comes to simplecart, but I have recently found it via google and I must say I am amazed. 

But as it always happen there are some problems, I will be using it with Polish payment site "PAYU" and I also need to have an option to send form containing order and method of payment to customer and to my mail. 

In documentation I found that in this version (v3) there is an option called "send form", but it is empty right now, if someone could give me a hint how to use it I would be a great help to him/her.

I hope to get an answer.

**Comment by ghost** [comment]
In the v3 config section, try this: 

checkout: { type: "SendForm" , url: "order.php" }

In v2 it's called CustomCheckout

**Comment by Swaartbaards** [comment]
Hi - im trying to integrate CustomCartjs with PayFast (a South African payment solution)

I know how to set up the 'sendform' option, but PayFast needs more information such as 'Merchat_ID' and 'Merchant_Key' which Payfast supplies me with when i open an account with them.

Where in the html or the simplecart.js would i supply the Merchant ID and Merchant Key so that when redirected from checkout to PayFast, it allows the redirection?

Ive been trying and trying but no luck

Help would be greatly appreciated!

Thanks,
Dean
