### ISSUE TITLE
Need help: Discounts and Coupons!

### ISSUE THREAD

**Issue by quickcleanpc** [wojodesign/simplecart-js#205]
I absolutely love Simplecartjs, but I have ran into a major problem. As you all may or may not know, Simplecartjs does not have a discount feature. This is crucial for me to have being that I am creating an affiliate page on my website for users and am in need of a promo code for discounts for users to use after they submit referrals. It would be nice if some one can assist me with some code from a button that will actually subtract a percentage of the entire cart. I have looked and looked and there is no practical solution for this.

So please if any one is kind enough to help me with this problem I have ran into it would be greatly appreciated!

My website: http://www.computersolutions.spruz.com/
My websites page that needs help: http://www.computersolutions.spruz.com/affiliate.htm

**Comment by integrate** [comment]
Hello.

Pobably I will able to help you. But to busy to do it right now.
I will review your description one more time later and will answer within 24 hours.

**Comment by brettwejrowski** [comment]
What checkout are you using?  It might me easiest to simply implement the discount system they have on your checkout system.  If you want to show the results of the discount in the cart, I would add a callback to the afterAdd and keep track of the original price in order to implement the discounts. 

Lets say that when the total in the cart is over 50 bucks, you give a 5% discount.  And when the total is over $100, you give a 10% discount.  It would look something like this:

``` javascript

simpleCart.bind( 'afterAdd', function( item ){

  var discountedPrice = 1;

  if( simpleCart.total > 100 ){
    discountedPrice = .9;
  } else if( simpleCart.total > 50 ){
    discountedPrice = .95;
  }

  simpleCart.each( function( i ) {
    if( !i.originalPrice ){
      i.originalPrice = i.price;
    } 
    i.price = i.originalPrice*discountedPrice;
  });
});

```

**Comment by integrate** [comment]
Events afterAdd and afterDelete will very useful.
I added it in one installation of simpleCartJS to implement rerquirement "Show cart only when it is not empty".
As I understand they could be added in current structure easy.
