### ISSUE TITLE
	 problems after deleting Article

### ISSUE THREAD

**Issue by crown** [wojodesign/simplecart-js#21]
hello .... when I delete an article (not always) to add another, replacing the last of the list.

**Comment by flatsix** [comment]
Same problem... but this goes for all items. It overwrites random items in the cart.

**Comment by lukevdp** [comment]
Basically if you have a variety of items and you keep adding different items to the cart, some items get overwritten. Seems to happen more often if you've deleted an item

**Comment by lukevdp** [comment]
After more testing I've found that I can't seem to get it to happen in IE, only firefox in chrome. Instead, in IE, after there are a certain amount of items in the cart, the whole cart dissapears

**Comment by crown** [comment]
i have the trouble with IE, safari and Firefox. :(  -the script is in 3 websites-

**Comment by schmig** [comment]
had the same problem. Guess it is because it requires a unique key for each product. To solve the problem, I did the following: add this html-tag within my simpleCart_shelfItem (within less- and greater-then signs): 
input class="item_key" value="$ID" type="hidden" 
 $ID is a numeric unique product-key. Then add one line of code to simpleCart.js:
 newItem.id = "c" + newItem['key']; 
do this just before the following comment line "/\* if the item already exists, update the quantity */"

**Comment by wojodesign** [comment]
fixed in 2.1
