### ISSUE TITLE
Passing Custom Values to PayPal

### ISSUE THREAD

**Issue by jonow** [wojodesign/simplecart-js#346]
I was wondering if there was a way to pass custom values to PayPal such as size or type. For example it has "Item price: $1.00" can I make it say below it "Type: AAAA"?

Also is it possible to remove the "Options" from the cart?

Here is the page https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=Qb58w6bGPtx3cS9ElKwpRRdVYdco0KePPmmZsvb2CBrMyfkURMWx-5Djrjm&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b081981f1b416268c54f4f7ecacedf8412cb63

Thanks

**Comment by dicentiu** [comment]
you should keep options because in the form options on paypal you will see your custom values. 

if you want "type" to appear in the final form on paypal you should add class = "item_type" in the shelf 
  http://simplecartjs.org/documentation/setup_initialization

if you have multiple custom values and don't want all to appear you should use excludeFromCheckout in SimpleCart initialization like this

excludeFromCheckout: ['field','type']

note that the array contains what follows after "item_" in the class used in the Shelf initialization.

**Comment by jonow** [comment]
Great! Thanks for your help.
