### ISSUE TITLE
Setting up the Email

### ISSUE THREAD

**Issue by Natasha24** [wojodesign/simplecart-js#80]
I want to use the email option on a site which is exchanging 'virtual' money more then  real money - hence needing the email option so that the email gets sent to my account.

I've downloaded the email.php file.

How would I go about including this in my SimpleCart set up?

**Comment by makuc** [comment]
Well, I take a closer look at index.html of the page that is shown in the example and figured out, that youo might need to download one more thing, which is: jquery-1.3.2.min

however, i am not sure, because I still did not upload my site to fully test and from preview it is still not working, but fell free to look a little dipper in this link:
https://github.com/thewojogroup/simplecart-js/tree/email

for the payment option all you have to do is set it in simpleCart.checkoutTo = Email

That's as far as I know. Hope that help, and write back, if you get it working. Because it mmight help me get it working properly later on.

Best regards, Armin.
