### ISSUE TITLE
add and remove via button and button changes

### ISSUE THREAD

**Issue by illya09** [wojodesign/simplecart-js#89]
Hi first thanks for such great code not a java expert by far, still learning but thanks to all!

I was wondering if anyone knows or could point me in the right direction any suggestions would be great.

I have a button

that calls a function and adds to cart

simpleCart.add('name=product','price='+total);

I would like to change that button  to remove  which would not be that hard

but adding such as

 onclick="simpleCart.items['c3'].remove();

to that button after it is clicked...

I am a bit stumped

So I guess the question is when someone hits the button (add to cart) above and then it changes (remove cart)

How can I know what id number it was?

Thanks Illya

**Comment by illya09** [comment]
function toggle(button) { 

```
if ( button.className === 'visible' ) {

    alert('hidden!');
    button.className = '';
    simpleCart.items['c1'].remove();

} else {

    alert('shown!');
    button.className = 'visible';
    simpleCart.add('name=someproduct','price=0.01' , 'id ='c1'); 
}
```

}

<CODE>
button id="a" onclick="toggle(this)">Button A</button
</CODE>

I'm getting there :-)

**Comment by wojodesign** [comment]
Hey illya09,  great input.  I should have thought of this issue earlier!

In the 2.2.dev branch, simpleCart.add() now returns in item if it is added successfully, otherwise it returns null.  so you can create the remove link by:

var item = simpleCart.add('name=someproduct','price=0.01' , 'id ='c1'); 

and then 

onclick="simpleCart.items['" + item.id + '"].remove();"
